language: objective-c
osx_image: xcode7
script:
  - xcodebuild test -workspace PusherSwift.xcworkspace -scheme PusherSwift -destination OS=8.4,name=iPhone\ 6 -sdk iphonesimulator8.4 ONLY_ACTIVE_ARCH=NO