language: objective-c
osx_image: xcode7.1
xcode_workspace: PusherSwift.xcworkspace
xcode_scheme: PusherSwift
xcode_sdk: iphonesimulator9.1
before_install:
  - brew update
  - brew install carthage
script:
  - xcodebuild test -workspace PusherSwift.xcworkspace -scheme PusherSwiftTests -destination OS=9.0,name=iPhone\ 6 -sdk iphonesimulator9.0 ONLY_ACTIVE_ARCH=NO
before_deploy:
  - carthage build --no-skip-current --verbose
  - carthage archive PusherSwift
deploy:
  provider: releases
  api_key:
    secure: JX093TPx+8Rvgd58s5KkmQQM0/i2cwSiSfRydqFHmN96wny5DHxxF0GOj/4kERHMS7R/gQYXCDtAoEAe0OP0ULD9PLH9D51G6KZQ1LKQPpzOK4ydJc3o9/CvcSrJpWmgSoGquOH0EITXxR4xaP3QrvmFx5mV48XHuZbMRjUlR8I=
  file:
    - "PusherSwift.framework.zip"
  skip_cleanup: true
  on:
    repo: pusher-community/pusher-websocket-swift
    tags: true
