language: objective-c
osx_image: xcode7
script:
  - xcodebuild test -workspace PusherSwift.xcworkspace -scheme PusherSwift -destination OS=9.0,name=iPhone\ 6 -sdk iphonesimulator9.0 ONLY_ACTIVE_ARCH=NO